In [1]:
import pandas as pd

In [3]:
dfs1 = pd.read_csv(
    "../datasets/local/vast-challenge-2021-mc3/csv-1700-1830.csv", encoding="latin1"
)
dfs2 = pd.read_csv(
    "../datasets/local/vast-challenge-2021-mc3/csv-1831-2000.csv", encoding="latin1"
)
dfs3 = pd.read_csv(
    "../datasets/local/vast-challenge-2021-mc3/csv-2001-2131.csv", encoding="latin1"
)

In [7]:
df_all = pd.concat([dfs1, dfs2, dfs3])

In [8]:
df_all

,type,date(yyyyMMddHHmmss),author,message,latitude,longitude,location
0,mbdata,20140123170000,POK,Follow us @POK-Kronos,NaN,NaN,NaN
1,mbdata,20140123170000,maha_Homeland,Don't miss a moment! Follow our live coverage...,NaN,NaN,NaN
2,mbdata,20140123170000,Viktor-E,Come join us in the Park! Music tonight at Abi...,NaN,NaN,NaN
3,mbdata,20140123170000,KronosStar,POK rally to start in Abila City Park. POK lea...,NaN,NaN,NaN
4,mbdata,20140123170000,AbilaPost,POK rally set to take place in Abila City Park...,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1210,mbdata,20140123213310,plasticParts,RT @AbilaPost unknown explosion heard from the...,NaN,NaN,NaN
1211,mbdata,20140123213345,klingon4real,RT @CentralBulletin explosion heard at dancing...,NaN,NaN,NaN
1212,mbdata,20140123213400,lindyT,RT @KronosStar There has been an explosion fro...,NaN,NaN,NaN
1213,mbdata,20140123213400,dolls4sale,RT @redisrad What was that? #boom,NaN,NaN,NaN
1214,mbdata,20140123213445,worldWatcher,RT @CentralBulletin explosion heard at dancing...,NaN,NaN,NaN

In [11]:
df_all["date"] = pd.to_datetime(df_all["date(yyyyMMddHHmmss)"], format="%Y%m%d%H%M%S")

In [12]:
df_all

,type,date(yyyyMMddHHmmss),author,message,latitude,longitude,location,date
0,mbdata,20140123170000,POK,Follow us @POK-Kronos,NaN,NaN,NaN,2014-01-23 17:00:00
1,mbdata,20140123170000,maha_Homeland,Don't miss a moment! Follow our live coverage...,NaN,NaN,NaN,2014-01-23 17:00:00
2,mbdata,20140123170000,Viktor-E,Come join us in the Park! Music tonight at Abi...,NaN,NaN,NaN,2014-01-23 17:00:00
3,mbdata,20140123170000,KronosStar,POK rally to start in Abila City Park. POK lea...,NaN,NaN,NaN,2014-01-23 17:00:00
4,mbdata,20140123170000,AbilaPost,POK rally set to take place in Abila City Park...,NaN,NaN,NaN,2014-01-23 17:00:00
...,...,...,...,...,...,...,...,...
1210,mbdata,20140123213310,plasticParts,RT @AbilaPost unknown explosion heard from the...,NaN,NaN,NaN,2014-01-23 21:33:10
1211,mbdata,20140123213345,klingon4real,RT @CentralBulletin explosion heard at dancing...,NaN,NaN,NaN,2014-01-23 21:33:45
1212,mbdata,20140123213400,lindyT,RT @KronosStar There has been an explosion fro...,NaN,NaN,NaN,2014-01-23 21:34:00
1213,mbdata,20140123213400,dolls4sale,RT @redisrad What was that? #boom,NaN,NaN,NaN,2014-01-23 21:34:00
1214,mbdata,20140123213445,worldWatcher,RT @CentralBulletin explosion heard at dancing...,NaN,NaN,NaN,2014-01-23 21:34:45

In [26]:
df_all.to_csv("../datasets/local/vast-challenge-2021-mc3/all_tweets.csv", index=False)

In [24]:
df_all.iloc[2100:2150]

,type,date(yyyyMMddHHmmss),author,message,latitude,longitude,location,date
1067,mbdata,20140123193013,teresaJ,RT @KronosStar The fire marshal has decided to...,NaN,NaN,NaN,2014-01-23 19:30:13
1068,mbdata,20140123193013,wiseWords,RT @KronosStar The fire marshal has decided to...,NaN,NaN,NaN,2014-01-23 19:30:13
1069,mbdata,20140123193013,farmboy,RT @CentralBulletin expansion of evacuation pe...,NaN,NaN,NaN,2014-01-23 19:30:13
1070,mbdata,20140123193013,ninjabob,RT @CentralBulletin expansion of evacuation pe...,NaN,NaN,NaN,2014-01-23 19:30:13
1071,mbdata,20140123193032,KronosQuoth,"The successful warrior is the average man, wit...",NaN,NaN,NaN,2014-01-23 19:30:32
1072,mbdata,20140123193032,KronosQuoth,The future heals descriptions of marvel #POKRa...,NaN,NaN,NaN,2014-01-23 19:30:32
1073,mbdata,20140123193054,KronosQuoth,A person who never made a mistake never tried ...,NaN,NaN,NaN,2014-01-23 19:30:54
1074,mbdata,20140123193100,phantomagate,RT @InternationalNews Neighborhood evacuations...,NaN,NaN,NaN,2014-01-23 19:31:00
1075,mbdata,20140123193100,muppiesRock,RT @InternationalNews Neighborhood evacuations...,NaN,NaN,NaN,2014-01-23 19:31:00
1076,mbdata,20140123193100,vetsRock,RT @InternationalNews Neighborhood evacuations...,NaN,NaN,NaN,2014-01-23 19:31:00
1077,mbdata,20140123193100,plasticParts,RT @NewsOnlineToday Additional residents being...,NaN,NaN,NaN,2014-01-23 19:31:00
1078,mbdata,20140123193100,sarajane,RT @martaO Now 1/2 hour late -- #pleasedontgiv...,NaN,NaN,NaN,2014-01-23 19:31:00
1079,mbdata,20140123193100,BlueVelvet,RT @sofitees @carlyscoffee best coffee in Abila,NaN,NaN,NaN,2014-01-23 19:31:00
1080,mbdata,20140123193124,junkman995,"I lost a bunch of weight, this stuff works! lo...",NaN,NaN,NaN,2014-01-23 19:31:24
1081,mbdata,20140123193124,KronosQuoth,Failure is the condiment that gives success it...,NaN,NaN,NaN,2014-01-23 19:31:24
1082,mbdata,20140123193124,Clevvah4Evah,Always flush out your ideas before presenting ...,NaN,NaN,NaN,2014-01-23 19:31:24
1083,mbdata,20140123193124,KronosQuoth,"You who are without sin, cast the first stone ...",NaN,NaN,NaN,2014-01-23 19:31:24
1084,mbdata,20140123193148,KronosQuoth,Limitations live only in our minds. But if we...,NaN,NaN,NaN,2014-01-23 19:31:48
1085,mbdata,20140123193148,Clevvah4Evah,Always flush out your ideas before presenting ...,NaN,NaN,NaN,2014-01-23 19:31:48
1086,mbdata,20140123193212,KronosQuoth,"In order to succeed, your desire for success s...",NaN,NaN,NaN,2014-01-23 19:32:12
1087,mbdata,20140123193212,KronosQuoth,"Success is the sum of small efforts, repeated ...",NaN,NaN,NaN,2014-01-23 19:32:12
1088,mbdata,20140123193212,KronosQuoth,The best time to plant a tree was 20 years ago...,NaN,NaN,NaN,2014-01-23 19:32:12
1089,mbdata,20140123193241,junkman995,time for a refill ? refill your meds online at...,NaN,NaN,NaN,2014-01-23 19:32:41
1090,mbdata,20140123193241,hotdrugs225,Hi! I advise you to visit this link hottips.kr...,NaN,NaN,NaN,2014-01-23 19:32:41
1091,mbdata,20140123193241,KronosQuoth,Only put off until tomorrow what you are willi...,NaN,NaN,NaN,2014-01-23 19:32:41
1092,mbdata,20140123193302,KronosQuoth,A person who never made a mistake never tried ...,NaN,NaN,NaN,2014-01-23 19:33:02
1093,mbdata,20140123193302,KronosQuoth,The best time to plant a tree was 20 years ago...,NaN,NaN,NaN,2014-01-23 19:33:02
1094,mbdata,20140123193302,KronosQuoth,Fall seven times and stand up eight. #KronosS...,NaN,NaN,NaN,2014-01-23 19:33:02
1095,mbdata,20140123193325,KronosQuoth,Knowledge is being aware of what you can do. W...,NaN,NaN,NaN,2014-01-23 19:33:25
1096,mbdata,20140123193325,KronosQuoth,I find that when you have a real interest in l...,NaN,NaN,NaN,2014-01-23 19:33:25
1097,mbdata,20140123193325,Clevvah4Evah,Youre the penultimate girlfriend! #POK #Rally ...,NaN,NaN,NaN,2014-01-23 19:33:25
1098,mbdata,20140123193346,KronosQuoth,The ones who are crazy enough to think they ca...,NaN,NaN,NaN,2014-01-23 19:33:46
1099,mbdata,20140123193400,microBanana,RT @michelleR See my #PhotoAlbum account for p...,NaN,NaN,NaN,2014-01-23 19:34:00
1100,mbdata,20140123193411,KronosQuoth,"If you want to achieve excellence, you can get...",NaN,NaN,NaN,2014-01-23 19:34:11
1101,mbdata,20140123193411,KronosQuoth,If you are not willing to risk the usual you w...,NaN,NaN,NaN,2014-01-23 19:34:11
1102,mbdata,20140123193411,KronosQuoth,Life is not about finding yourself. Life is ab...,NaN,NaN,NaN,2014-01-23 19:34:11
1103,mbdata,20140123193432,KronosQuoth,The question isnt who is going to let me; its ...,NaN,NaN,NaN,2014-01-23 19:34:32
1104,mbdata,20140123193454,KronosQuoth,You can never cross the ocean until you have t...,NaN,NaN,NaN,2014-01-23 19:34:54
1105,mbdata,20140123193507,AbilaPost,another police unit has been dispatched to hel...,NaN,NaN,NaN,2014-01-23 19:35:07
1106,mbdata,20140123193507,OnlytheTruth,Look at 'em run!,NaN,NaN,NaN,2014-01-23 19:35:07
1107,mbdata,20140123193507,hngohebo_ABILAPOST,bicyclist in hit and run accident at 500 block...,NaN,NaN,NaN,2014-01-23 19:35:07
1108,mbdata,20140123193507,KronosStar,The bicyclist in the 500 block of Schaber acci...,NaN,NaN,NaN,2014-01-23 19:35:07
1109,mbdata,20140123193507,AbilaPoliceDepartment,Abila Police Department reports pursuit of sus...,NaN,NaN,NaN,2014-01-23 19:35:07
1110,mbdata,20140123193507,trapanitweets,Henri -bike guy- done talking to coppers now l...,36.054,24.901,NaN,2014-01-23 19:35:07
1111,mbdata,20140123193507,brewvebeenserved,Going to give the biker a coffee!! He's Bean S...,36.054,24.901,NaN,2014-01-23 19:35:07
1112,ccdata,20140123193507,NaN,RECKLESS/HAZARADOUS DRIVER-IN PROGRESS,NaN,NaN,Egeou Ave / Polvo St,2014-01-23 19:35:07
1113,mbdata,20140123193522,KronosQuoth,"Thinking should become your capital asset, no ...",NaN,NaN,NaN,2014-01-23 19:35:22
1114,mbdata,20140123193522,Clevvah4Evah,"In edition, you should always add instead of m...",NaN,NaN,NaN,2014-01-23 19:35:22
1115,mbdata,20140123193522,KronosQuoth,Remember that not getting what you want is som...,NaN,NaN,NaN,2014-01-23 19:35:22
1116,mbdata,20140123193547,KronosQuoth,People often say that motivation doesn't last....,NaN,NaN,NaN,2014-01-23 19:35:47